import test from 'node:test';
import assert from 'node:assert';
import { ResponseDlp } from '../src/response-dlp.ts';
import { MasterDetector } from '../src/detectors/index.ts';
import { SessionVault } from '../src/vault.ts';
import { PolicyEngine } from '../src/policy.ts';

test('ResponseDlp restores legitimate placeholders while leaving clean text intact', () => {
  const detector = new MasterDetector();
  const dlp = new ResponseDlp(detector);
  const vault = new SessionVault();

  // Register legitimate placeholder
  const placeholder = vault.getPlaceholder('Jean Dupont', 'PERSON');
  const response = `Bonjour ${placeholder}, votre compte est activé.`;

  const result = dlp.sanitizeResponse(response, vault);
  assert.strictEqual(result.blocked, false);
  assert.strictEqual(result.text, 'Bonjour Jean Dupont, votre compte est activé.');
  assert.strictEqual(result.newLeaksDetected.length, 0);
  assert.strictEqual(result.deanonymizedCount, 1);
});

test('ResponseDlp catches and redacts newly leaked secrets generated by the model', () => {
  const detector = new MasterDetector();
  const dlp = new ResponseDlp(detector);
  const vault = new SessionVault();

  const placeholder = vault.getPlaceholder('Alice', 'PERSON');
  // Model hallucinates an unauthorized raw API key and an internal IP
  const responseWithLeak = `Merci ${placeholder}. Voici la clé secrète: sk-proj-1234567890abcdef12345678 et le serveur 10.0.0.42.`;

  const result = dlp.sanitizeResponse(responseWithLeak, vault);
  assert.strictEqual(result.blocked, false);
  assert.strictEqual(result.newLeaksDetected.length, 2);

  // Alice restored, but leaked key and internal IP redacted!
  assert.ok(result.text.includes('Merci Alice.'));
  assert.ok(result.text.includes('[REDACTED_SECRET]'));
  assert.ok(result.text.includes('[REDACTED_INTERNAL_IP]'));
  assert.strictEqual(result.text.includes('sk-proj-1234567890abcdef12345678'), false);
  assert.strictEqual(result.text.includes('10.0.0.42'), false);
});

test('ResponseDlp blocks response if policy mandates blocking on specific response leaks', () => {
  const detector = new MasterDetector();
  const policy = new PolicyEngine({
    rules: [
      {
        id: 'block-response-nir',
        match: { entities: ['NIR'] },
        action: 'BLOCK',
        reason: 'Models must never output raw social security numbers',
      },
    ],
  });
  const dlp = new ResponseDlp(detector, policy);
  const vault = new SessionVault();

  // Model outputs a French NIR that was not in the vault
  const responseWithNir = 'Le numéro de sécurité sociale retrouvé est 1850575108123.';
  const result = dlp.sanitizeResponse(responseWithNir, vault);

  assert.strictEqual(result.blocked, true);
  assert.strictEqual(result.blockReason, 'Models must never output raw social security numbers');
});
